---
- name: Deploy Alarm Platform with Helm
  kubernetes.core.helm:
    name: alarm
    chart_ref: ../../charts/alarm
    release_namespace: alarm-system
    create_namespace: true
    state: present
