---
- name: Ensure alarm namespace exists
  kubernetes.core.k8s:
    name: alarm-system
    api_version: v1
    kind: Namespace
    state: present


- name: Deploy Alarm Platform with Helm
  kubernetes.core.helm:
    name: alarm
    chart_ref: ../../charts/alarm
    release_namespace: alarm-system
    create_namespace: true
    state: present
