apiVersion: apps/v1
kind: Deployment
metadata:
  name: alarm-frontend
  namespace: alarm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alarm-frontend
  template:
    metadata:
      labels:
        app: alarm-frontend
    spec:
      containers:
      - name: frontend
        image: alarm-frontend
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: alarm-frontend-service
  namespace: alarm-system
spec:
  selector:
    app: alarm-frontend
  ports:
  - port: 80
    targetPort: 80
  type: NodePort